### ISSUE TITLE
User Authentication Without Prompt

### ISSUE THREAD

**Issue by tasinclair1** [Microsoft/powerbi-powershell#49] opened 2018-07-10 12:30 UTC
I currently have a user account set up in AzureAD with a PowerBI Pro licence assigned exclusivly for the use of embedding reports within my application on behalf of users who do not have PowerBI Pro licences as described [here](https://github.com/Microsoft/PowerBI-developer-samples#app-owns-data-samples).

I would like to use the credentials of this existing user account to authenticate with the PowerShell libriaries to build some utilities to manage the reports in this application but it appears that the only way to authenticate as a user is via a pop up which is not ideal for my use case.

Is there currently any way to authenticate with the PowerBI Powershell libraries without this prompt? Ideally I would like to pass in a PSCredential made up of the user account's Username and Password along with the clientId of the registered application in AzureAD to recieve the access token.

I have found an [example](https://github.com/DevScope/powerbi-powershell-modules/blob/9c5a4a1c7ca27d064f10e9c3853afe64cd8d603b/Modules/PowerBIPS/PowerBIPS.psm1#L139) which manually imports [Microsoft.IdentityModel.Clients.ActiveDirectory](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory?view=azure-dotnet) in order to authenticate using username/password/clientId but this feels like a messy workaround.

Is there any plan to add user authentication in this way to the official PowerBI PowerShell cmdlets?

Thanks.

**Comment by CodeCyclone** [comment] 2018-07-13 00:42
We do support username/password for service accounts by suppling the -ServicePrincipal switch along with -Credential, see https://docs.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.profile/connect-powerbiserviceaccount?view=powerbi-ps.

Worth mentioning, many of Power BI's APIs don't support this type of authentication (AAD application only). Currently only the Admin APIs support it - https://docs.microsoft.com/en-us/rest/api/power-bi/admin. In the documentation you will notice "Application only .. permissions are supported"

**Comment by CodeCyclone** [comment] 2018-07-19 22:22
Related\duplicate of issue #51. Issue is in the API not the cmdlet but I will keep issue open for tracking.

**Comment by fmms** [comment] 2018-10-03 11:35
I think this is the sames as #59

**Comment by JanMulkens** [comment] 2018-10-11 12:07
Not sure if this will help, but here it goes.
I've been having the same issue while calling the REST API from within powershell.
Apparantly I had given a different redirect URI during my API call compared to the one I gave during app registration.

I'm now using "urn:ietf:wg:oauth:2.0:oob" as redirect URI with the native app setting and everything works perfectly.

**Comment by dfaa502** [comment] 2018-11-01 22:08
Any update on the related bug?

**Comment by CodeCyclone** [comment] 2018-11-27 00:07
Thanks @JanMulkens, yes you need that as your redirect for the AAD app. In a future update we will allow the redirect to be passed in. 

For the next release, the Connect-PowerBIServiceAccount will support -Credential (Get-Credential) which you can also do without prompting - https://blogs.msdn.microsoft.com/koteshb/2010/02/12/powershell-how-to-create-a-pscredential-object/

This is without the -ServiceAccount flag being specified. Some APIs early next year will support ServicePrincipal, till then this should be a viable workaround. Note this only works on Windows OS (in either Windows PowerShell or PowerShell Core).

**Comment by CodeCyclone** [comment] 2018-12-01 00:17
Released in https://www.powershellgallery.com/packages/MicrosoftPowerBIMgmt/1.0.342

**Closed by CodeCyclone** 2018-12-01 00:17 UTC
Labels: external bug
