### ISSUE TITLE
MicrosoftPowerBIMgmt.Profile source location is not valid

### ISSUE THREAD

**Issue by skcary77** [Microsoft/powerbi-powershell#81] opened 2018-09-12 13:08 UTC
I'm trying to install the MicrosoftPowerBIMgmt module. I run the following command:

`Install-Module -Name MicrosoftPowerBIMgmt -Scope CurrentUser` 

I received the following message: 
`WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/MicrosoftPowerBIMgmt.Profile/1.0.326' is not
 valid.
PackageManagement\Install-Package : Package 'MicrosoftPowerBIMgmt.Profile' failed to download.`

Any ideas whats happening?

**Comment by CodeCyclone** [comment] 2018-11-26 22:58
Try updating NuGet and PowerShellGet libraries by following these instructions - https://docs.microsoft.com/en-us/powershell/gallery/installing-psget 

If that doesn't work, there might be an issue with your PSGallery Source Location or an issue with either PowerShellGet or PowerShell Gallery. You might have to open an issue at https://github.com/powershell/powershellget to get this resolved. If the issue isn't getting resolved, open a support ticket to gain more traction.

**Comment by CodeCyclone** [comment] 2018-11-30 23:47
Closing as this is external to this repo and an issue in PSGallery

**Closed by CodeCyclone** 2018-11-30 23:47 UTC
Labels: bug
